import '../entities/trip.dart';
import '../entities/trip_expense.dart';

/// All trip and trip-expense persistence goes through this repository — the
/// presentation layer never touches Hive directly (§18.8).
abstract class TripRepository {
  List<Trip> getAllTrips();

  /// Creates a new trip. `id`/`createdAt`/`updatedAt` are generated by the
  /// implementation. [homeCurrency] must be passed in by the caller as
  /// whatever the global home currency is *at this moment* — the
  /// repository stores it verbatim as the trip's permanent snapshot
  /// (§5.2/§20.7) and never re-derives it later.
  void createTrip({
    required String name,
    required String localCurrency,
    required String homeCurrency,
    required double totalBudget,
  });

  /// §5.2 edit — `homeCurrency` is deliberately not editable (§20.7).
  void editTrip({
    required String id,
    required String name,
    required String localCurrency,
    required double totalBudget,
  });

  void archiveTrip(String id);

  /// Deletes the trip and, since an expense can't outlive its trip, every
  /// expense that belongs to it.
  void deleteTrip(String id);

  List<TripExpense> getExpensesForTrip(String tripId);

  void addExpense({
    required String tripId,
    required String title,
    required double amountLocal,
    required ExpenseCategory category,
    String? note,
    required DateTime spentAt,
  });

  void editExpense({
    required String id,
    required String title,
    required double amountLocal,
    required ExpenseCategory category,
    String? note,
    required DateTime spentAt,
  });

  void deleteExpense(String id);
}
