import '../entities/alert_trigger_history.dart';
import '../entities/rate_alert.dart';

/// All alert and trigger-history persistence goes through this repository —
/// the presentation layer never touches Hive directly (§18.8).
abstract class AlertRepository {
  List<RateAlert> getAllAlerts();

  /// Creates a new alert. `id`/`createdAt`/`updatedAt` are generated by the
  /// implementation; a new alert always starts `isActive: true` and
  /// `isArmed: true`.
  void createAlert({
    required String baseCurrency,
    required String quoteCurrency,
    required double targetRate,
    required AlertDirection direction,
  });

  /// §6.2 edit. Re-arms the alert (`isArmed: true`) — changing the pair,
  /// target, or direction changes what "the trigger zone" even means, so
  /// any prior armed/disarmed state described a condition that no longer
  /// applies.
  void editAlert({
    required String id,
    required String baseCurrency,
    required String quoteCurrency,
    required double targetRate,
    required AlertDirection direction,
  });

  void deleteAlert(String id);

  void activateAlert(String id);

  void deactivateAlert(String id);

  /// Persists the full alert state produced by a check cycle
  /// (`lastCheckedAt`/`lastTriggeredAt`/`isArmed`) — distinct from the
  /// user-driven mutations above, which is why it takes the whole entity
  /// rather than a narrower set of named fields.
  void saveCheckedAlert(RateAlert alert);

  void addTriggerHistory(AlertTriggerHistory history);

  List<AlertTriggerHistory> getTriggerHistoryForAlert(String alertId);
}
